yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings

from .models import Post, Group


def index(request):
    posts = Post.objects.all()[:settings.POST_COUNT]
    context = {
        'posts': posts
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:settings.POST_COUNT]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>
    <meta charset="UTF-8">
    <title> {% block title %} ПОСЛЕДНИЕ ОБНОВЛЕНИЯ НА САЙТЕ {% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/fav/fav.ico' type='image' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
  </head>
  <body>
  {% include 'includes/header.html' %}
  <main>
      {% block content %}
      {% endblock %}
  </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
{% load static %}
<footer class="page-footer font-small blue border-top">
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'posts:index' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
        </div>
    </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества: {{ group }} {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
  <article>
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
    <hr />
  </article>
  {% endfor %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} Последние обновления на сайте. {% endblock %}
{% block content %}
<div class="container py-5">
  <h1>Последние обновления на сайте</h1>
  <article>
    {% for post in posts %}
    <ul>
      <li>Автор: {{ post.author.get_full_name }}</li>
      <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
    </ul>
    <p>{{ post.text }}</p>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    <hr />
    {% endfor %}
  </article>
</div>
{% endblock %}